'use client';

import React, { useEffect, useRef, useState } from 'react';
import { Play, Pause, RotateCcw, Settings, Info, ChevronRight, Activity } from 'lucide-react';
import { MarkdownRenderer } from '../chat/MarkdownRenderer';

interface Control {
  id: string;
  label: string;
  min: number;
  max: number;
  value: number;
  step?: number;
}

export const PhysicsBlock = ({ code }: { code: string }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [isPlaying, setIsPlaying] = useState(true);
  const [config, setConfig] = useState<any>(null);
  const [controls, setControls] = useState<Record<string, number>>({});
  const p5Instance = useRef<any>(null);

  const [resetKey, setResetKey] = useState(0);

  const handleReset = () => {
    setResetKey(prev => prev + 1);
    if (config?.controls) {
      const initialControls: Record<string, number> = {};
      config.controls.forEach((c: any) => {
        initialControls[c.id] = c.value;
      });
      setControls(initialControls);
    }
    setIsPlaying(true);
  };

  useEffect(() => {
    try {
      const parsed = JSON.parse(code);
      if (parsed.type === 'physics_lab') {
        setConfig(parsed);
        const initialControls: Record<string, number> = {};
        parsed.controls?.forEach((c: Control) => {
          initialControls[c.id] = c.value;
        });
        setControls(initialControls);
      }
    } catch (e) {
      setConfig({ sketch: code, explanation: "Real-time physics simulation generated by Neural AI." });
    }
  }, [code]);

  useEffect(() => {
    if (!containerRef.current || !config?.sketch) return;

    const initP5 = async () => {
      const p5Module = await import('p5');
      const p5 = p5Module.default;

      const sketch = (p: any) => {
        p.controls = controls;
        try {
          const sketchLogic = new Function('p', config.sketch);
          sketchLogic(p);
        } catch (err) {
          console.error('Sketch Error:', err);
        }
      };

      if (p5Instance.current) p5Instance.current.remove();
      p5Instance.current = new p5(sketch, containerRef.current!);
      if (!isPlaying) p5Instance.current.noLoop();
    };

    initP5();
    return () => p5Instance.current?.remove();
  }, [config?.sketch, resetKey]);

  useEffect(() => {
    if (p5Instance.current) {
      p5Instance.current.controls = controls;
    }
  }, [controls]);

  useEffect(() => {
    if (p5Instance.current) {
      if (isPlaying) p5Instance.current.loop();
      else p5Instance.current.noLoop();
    }
  }, [isPlaying]);

  if (!config) return null;

  return (
    <div key={resetKey} className="my-10 rounded-[2.5rem] border border-white/10 bg-black overflow-hidden shadow-[0_0_50px_-12px_rgba(0,0,0,0.5)] animate-in zoom-in-95 duration-1000">
      <div className="flex items-center justify-between px-8 py-5 border-b border-white/5 bg-zinc-900/80 backdrop-blur-2xl">
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-2xl bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20">
            <Activity size={20} className="text-emerald-400" />
          </div>
          <div>
            <span className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-500/60 block leading-none mb-1.5">Neural Physics Lab</span>
            <span className="text-sm font-bold text-white tracking-tight">Interactive Simulation</span>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button type="button" onClick={() => setIsPlaying(!isPlaying)} className="p-3 hover:bg-white/5 rounded-xl transition-all text-white border border-white/5 bg-white/5">
            {isPlaying ? <Pause size={18} fill="currentColor" /> : <Play size={18} fill="currentColor" />}
          </button>
          <button type="button" onClick={handleReset} className="p-3 hover:bg-white/5 rounded-xl transition-all text-white border border-white/5">
            <RotateCcw size={18} />
          </button>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row">
        {/* Left: Animation & Controls */}
        <div className="flex-1 border-r border-white/5">
          <div ref={containerRef} className="w-full bg-[#050505] aspect-video relative" />
          
          {/* Control Panel */}
          {config.controls && (
            <div className="p-8 bg-zinc-900/30 grid grid-cols-1 md:grid-cols-2 gap-6 border-t border-white/5">
              {config.controls.map((c: Control) => (
                <div key={c.id} className="space-y-3">
                  <div className="flex justify-between items-center">
                    <label className="text-[10px] font-bold uppercase tracking-widest text-zinc-500">{c.label}</label>
                    <span className="text-xs font-mono font-bold text-emerald-400">{controls[c.id] !== undefined ? controls[c.id].toFixed(2) : '0.00'}</span>
                  </div>
                  <input 
                    type="range" min={c.min} max={c.max} step={c.step || 0.1}
                    value={controls[c.id]} 
                    onChange={(e) => setControls(prev => ({ ...prev, [c.id]: parseFloat(e.target.value) }))}
                    className="w-full h-1.5 bg-zinc-800 rounded-lg appearance-none cursor-pointer accent-emerald-500"
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Right: Explanation */}
        <div className="w-full lg:w-[400px] bg-zinc-900/50 backdrop-blur-md p-8 overflow-y-auto max-h-[600px] scrollbar-hide">
          <div className="flex items-center gap-2 mb-6">
            <Info size={16} className="text-blue-400" />
            <h3 className="text-[10px] font-black uppercase tracking-widest text-zinc-400">Expert Analysis</h3>
          </div>
          <div className="prose prose-invert prose-sm max-w-none">
            <MarkdownRenderer content={config.explanation} enableVisuals={false} />
          </div>
          
          <div className="mt-10 p-5 rounded-2xl bg-emerald-500/5 border border-emerald-500/10">
            <div className="flex items-center gap-2 mb-3">
              <Settings size={14} className="text-emerald-400" />
              <span className="text-[9px] font-bold uppercase tracking-widest text-emerald-500/60">Live Metrics</span>
            </div>
            <div className="space-y-2">
              {Object.entries(controls).map(([key, val]) => (
                <div key={key} className="flex justify-between items-center">
                  <span className="text-[10px] text-zinc-500 font-bold uppercase">{key}</span>
                  <span className="text-xs font-mono text-white font-bold">{(val || 0).toFixed(3)}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
