'use client';

import React, { useEffect, useRef, useState } from 'react';
import { Box, Settings, Info, Activity, Maximize2, RotateCcw } from 'lucide-react';
import { MarkdownRenderer } from '../chat/MarkdownRenderer';
import { useTheme } from 'next-themes';

interface Control {
  id: string;
  label: string;
  min: number;
  max: number;
  value: number;
  step?: number;
}

export const ThreeBlock = ({ code }: { code: string }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [config, setConfig] = useState<any>(null);
  const [controls, setControls] = useState<Record<string, number>>({});
  const controlsRef = useRef<Record<string, number>>({});
  const [resetKey, setResetKey] = useState(0);
  const rendererRef = useRef<any>(null);
  const requestRef = useRef<number | null>(null);
  const { resolvedTheme } = useTheme();

  const handleReset = () => {
    setResetKey(prev => prev + 1);
    if (config?.controls) {
      const initialControls: Record<string, number> = {};
      config.controls.forEach((c: Control) => {
        initialControls[c.id] = c.value;
      });
      setControls(initialControls);
      controlsRef.current = initialControls;
    }
  };

  useEffect(() => {
    try {
      const parsed = JSON.parse(code);
      if (parsed.type === '3d_studio') {
        setConfig(parsed);
        const initialControls: Record<string, number> = {};
        parsed.controls?.forEach((c: Control) => {
          initialControls[c.id] = c.value;
        });
        setControls(initialControls);
        controlsRef.current = initialControls;
      }
    } catch (e) {
      setConfig({ sketch: code, explanation: "3D scene generated by Neural AI Studio." });
    }
  }, [code]);

  useEffect(() => {
    let isMounted = true;
    if (!containerRef.current || !config?.sketch) return;

    const initThree = async () => {
      const THREE = await import('three');
      
      if (!containerRef.current || !isMounted) return;

      const width = containerRef.current.clientWidth;
      const height = containerRef.current.clientHeight;

      const scene = new THREE.Scene();
      const camera = new THREE.PerspectiveCamera(75, width / height, 0.1, 1000);
      camera.position.z = 5;

      const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
      renderer.setSize(width, height);
      renderer.setPixelRatio(window.devicePixelRatio);
      
      if (isMounted && containerRef.current) {
        containerRef.current.appendChild(renderer.domElement);
        rendererRef.current = renderer;
      } else {
        renderer.dispose();
        return;
      }

      try {
        const sanitizedCode = config.sketch
          .replace(/const\s+(scene|camera|THREE)\s*=/g, '// $&')
          .replace(/let\s+(scene|camera|THREE)\s*=/g, '// $&')
          .replace(/var\s+(scene|camera|THREE)\s*=/g, '// $&');

        const sketchLogic = new Function('THREE', 'scene', 'camera', 'controls', sanitizedCode);
        const { update } = sketchLogic(THREE, scene, camera, controlsRef.current) || {};
        
        const animate = () => {
          if (!isMounted) return;
          if (update) update(controlsRef.current);
          renderer.render(scene, camera);
          requestRef.current = requestAnimationFrame(animate);
        };
        animate();
      } catch (err) {
        console.error('Three.js Error:', err);
      }
    };

    initThree();

    return () => {
      isMounted = false;
      if (requestRef.current) cancelAnimationFrame(requestRef.current);
      if (rendererRef.current) {
        const renderer = rendererRef.current;
        renderer.dispose();
        if (containerRef.current?.contains(renderer.domElement)) {
          containerRef.current.removeChild(renderer.domElement);
        }
        rendererRef.current = null;
      }
    };
  }, [config?.sketch, resetKey]);

  // Sync state to Ref for zero-latency animation updates
  const updateControl = (id: string, val: number) => {
    setControls(prev => ({ ...prev, [id]: val }));
    controlsRef.current[id] = val;
  };

  if (!config) return null;

  return (
    <div key={resetKey} className="my-10 rounded-[2.5rem] border border-[var(--border)] bg-[var(--bg-card)] overflow-hidden shadow-2xl animate-in zoom-in-95 duration-1000">
      <div className="flex items-center justify-between px-8 py-5 border-b border-[var(--border)] bg-[var(--bg-card)]/80 backdrop-blur-2xl">
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-2xl bg-blue-500/10 flex items-center justify-center border border-blue-500/20 text-blue-400">
            <Box size={20} />
          </div>
          <div>
            <span className="text-[10px] font-black uppercase tracking-[0.3em] text-blue-500/60 block leading-none mb-1.5">Neural 3D Studio</span>
            <span className="text-sm font-bold text-[var(--text-main)] tracking-tight">Interactive WebGL Scene</span>
          </div>
        </div>
        <button type="button" onClick={handleReset} className="p-3 hover:bg-[var(--bg-sidebar)] rounded-xl transition-all text-[var(--text-main)] border border-[var(--border)]">
          <RotateCcw size={18} />
        </button>
      </div>

      <div className="flex flex-col lg:flex-row">
        <div className="flex-1 bg-gradient-to-b from-[var(--bg-sidebar)] to-[var(--bg-card)] relative min-h-[400px]">
          <div ref={containerRef} className="w-full h-full absolute inset-0" />
          
          {config.controls && (
            <div className="absolute bottom-6 left-6 right-6 p-6 bg-[var(--bg-card)]/40 backdrop-blur-xl rounded-3xl border border-[var(--border)] grid grid-cols-1 md:grid-cols-2 gap-6">
              {config.controls.map((c: Control) => (
                <div key={c.id} className="space-y-2">
                  <div className="flex justify-between items-center px-1">
                    <label className="text-[9px] font-black uppercase tracking-widest text-[var(--text-muted)]">{c.label}</label>
                    <span className="text-[10px] font-mono font-bold text-blue-400">{Number(controls[c.id] || c.value).toFixed(2)}</span>
                  </div>
                  <input 
                    type="range" min={c.min} max={c.max} step={c.step || 0.01}
                    value={controls[c.id] || c.value} 
                    onChange={(e) => updateControl(c.id, parseFloat(e.target.value))}
                    className="w-full h-1 bg-[var(--border)] rounded-full appearance-none cursor-pointer accent-blue-500"
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="w-full lg:w-[400px] bg-[var(--bg-card)] p-8 overflow-y-auto max-h-[600px] scrollbar-hide border-l border-[var(--border)]">
          <div className="flex items-center gap-2 mb-6">
            <Info size={16} className="text-blue-400" />
            <h3 className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)]">Scene Intelligence</h3>
          </div>
          <div className={`prose ${resolvedTheme === 'dark' ? 'prose-invert' : ''} prose-sm max-w-none`}>
            <MarkdownRenderer content={config.explanation} enableVisuals={false} />
          </div>
          
          <div className="mt-10 p-6 rounded-[2rem] bg-blue-500/5 border border-blue-500/10">
            <div className="flex items-center gap-2 mb-4">
              <Settings size={14} className="text-blue-400" />
              <span className="text-[9px] font-bold uppercase tracking-widest text-blue-500/60">Spatial Parameters</span>
            </div>
            <div className="space-y-3">
              {Object.entries(controls).map(([key, val]) => (
                <div key={key} className="flex justify-between items-center">
                  <span className="text-[10px] text-[var(--text-muted)] font-bold uppercase">{key}</span>
                  <span className="text-[11px] font-mono text-[var(--text-main)] font-bold">{Number(val || 0).toFixed(3)}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
